module OneNine where
-- | Each of the folloiwng two procedures defines a method for adding two
-- | positive integers in terms of the procedures `succ`, which increments
-- | its arguments by 1, and `pred`, which decrements its argument by 1.

add a b = if a == 0 then b else succ (add (pred a) b)
add' a b = if a == 0 then b else add (pred a) (succ b)

-- Using the substitution model, illustrate the process generated by each
-- procedure in evaluating add 4 5. Are these processes iterative or
-- recursive?
